### ISSUE TITLE
[FEATURE] Clarity around webhook-broker project

### ISSUE THREAD

**Issue by dcoty** [imyousuf/webhook-broker#69]
**Is your feature request related to a problem? Please describe.**
I am pretty new to Go programming. I understand this is a pub/sub broker, but why does this exist, and how do you use it?

**Describe the solution you'd like**
A better description of this project, what problem it's trying to solve, and why.  i see that it It aims to solve the inter service communication problem, but what problem is this? can more detail be provided? 

Also, working examples on how to use this (rather than multiple ways to set this up)would be great. This would help people seeing this repo help to understand how to use this.

**Describe alternatives you've considered**
Diving through the code in an attempt to put together everything this does to find clues on why this exists and how to use it. But this is hopeless if i don't have context on the what, how and why of this project.

**Additional context**
I understand the intention here is to provide a pub/sub broker to those who can use it to solve whatever problems they have. but it would really benefit the community overall if a better description on what this is, what problem it solves and how, as well as good usage examples were provided.

**Comment by imyousuf** [comment]
Hey! Thank you @dcoty so much for such good questions and feedback. I will definitely consider adding the details in a more structure manner. Please let me know whether explanation below helps to address the point you made; I would love to work on the narrative with you. Thank you.

The project started from the need we had internally and for us these are pretty straightforward challenges, I can see perfectly why it would not as clear to others. So let me try to elaborate here to unblock you what the project is for before I put together some documentation as you suggested.

In a system where there are multiple services it is natural that there is inter service dependency which are asynchronous in nature. Lets see an example to understand it. There is a SaaS product; when a user registration happens there will be a congratulatory welcome email sent to the user. Here, for the sake of this conversation, lets assume there is a service that is responsible for sending out email to the end user; so the registration action will trigger the email; but email sending does not necessarily need to block the registration process; so it is asynchronous in nature. In this example, the **registration service** will call the **email service** to send out the _welcome email_ to a certain email-address. Now when this call is made, there is no guarantee that **email service** is available so how does registration service ensure sending the message. Here is where the broker comes in. The **broker** is a simple service that does very straightforward work and is deployed with high-availability in mind and it _guarantees_ delivery of a message that it received with transparency at least once.

So in the example above -
**registration service** ---------- Email address and welcome email ------> **broker** ------ relay message -------> **email service**
What broker introduces here is the asynchronous, non-blocking, guarantee of delivery.

Some of the use cases we are considering using it for is -

1. Message passing between systems where the use cases are -
1.1. Propagate changes to objects for search-index indexing
1.2. Propagate changes to objects for Authentication and Authorization computation
1.3. For triggering asynchronous processing/denormalizing objects
1. For delivery of Public API Webhook events.

**Comment by dcoty** [comment]
@imyousuf Thanks for addressing this! This makes more sense now. I would suggest you use this in your readme to help clear things up for people not so seasoned in this such as myself. If there is a general usage example somewhere, that would do it( at least in my opinion anyway)

With that said, this is an interesting thing. To frame it to my perspective( high level)it looks like something somewhat comparable to something like rabbitMQ or Amazon SQS. I'm probably simplifying it though( sorry about that).

**Comment by imyousuf** [comment]
@dcoty Simplification is the motivation of this project. Yes from a high level the goal internally for us to combine Celery, RabbitMQ, SQS and even Kinesis (not not streaming and batching use case) into a single product simplifying overall system architecture reducing the need to have system components deployed; for example, with SQS or Celery you would have your service deployed as a web application and then need a worker for async tasks/processing. Keep in mind it will have pros-cons vs SQS/RabbitMQs; for example you would still want them for long running tasks (some that spans minutes). Does it make sense?

I will issue a PR modifying the README and will request your review. If you are looking at usage example the integration test could serve as a [usage](https://github.com/imyousuf/webhook-broker/blob/main/integration-test/main.go) example. We will soon release Python and NodeJS wrappers around w7b6; I will tag you to them.

**Comment by imyousuf** [comment]
@dcoty Please find the PR #70 addressing the information change in the README. Please share your thoughts.
